dina-share:
  image: tianon/true
  volumes:
    - ./mysql-datadir:/var/lib/mysql:z
    - ./mysql-shr:/shr:z
    - ./mysql-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql-conf.d:/etc/mysql/conf.d:z
    - ./localdb-run.sh:/localdb-run.sh:rw
    - ./deployments:/opt/jboss/wildfly/standalone/deployments:z
    - ./wildfly-conf/configuration:/opt/keycloak/standalone/configuration:z

fs-api:
  image: tianon/true
  volumes:
    - ./nginx-conf:/etc/nginx/conf.d:rw
    - ./nginx-certs:/etc/nginx/ssl:rw
    - ./nginx-logs:/etc/nginx/logs:rw

dina-mysql:
  image: mysql:latest
  command: "sh /localdb-run.sh"
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=password12
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak
  ports:
    - "3306:3306"
  volumes_from:
    - dina-share

dina-keycloak:
  image: jboss/keycloak-mysql:1.6.1.Final
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak
    - VIRTUAL_HOST=sso.dina-web
  ports:
    - "8080:8080"
    - "9990:9990"
  links:
    - dina-mysql:mysql
  volumes_from:
    - dina-share

as:
  image: dina/collections-api
  environment:
    - TZ=Europe/Stockholm
  links:
    - dina-keycloak
    - dina-mysql

ws-api:
  image: nginx
  environment:
    - VIRTUAL_HOST=beta-api.dina-web.net
    - VIRTUAL_PORT=443
    - VIRTUAL_PROTO=https
    - CERT_NAME=shared
  links:
    - as
    - solr
  volumes_from:
    - fs-api

solr:
  build: solr
  links:
    - dina-mysql:mysql
  ports:
    - "8983:8983"
