dina-share:
  image: tianon/true
  volumes:
    - ./mysql-datadir:/var/lib/mysql:z
    - ./mysql-shr:/shr:z
    - ./mysql-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql-conf.d:/etc/mysql/conf.d:z
    - ./deployments:/opt/jboss/wildfly/standalone/deployments:z
    - ./wildfly-conf/configuration:/opt/keycloak/standalone/configuration:z

dina-mysql:
  image: mysql:latest
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=password12
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak
  ports:
    - "3306:3306"
  volumes_from:
    - dina-share

dina-keycloak:
  image: jboss/keycloak-mysql:1.6.1.Final
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak
    - VIRTUAL_HOST=sso.dina-web
  ports:
    - "8080:8080"
    - "9990:9990"
  links:
    - dina-mysql:mysql
  volumes_from:
    - dina-share

dina-wildfly:
  build: .
  environment:
    - TZ=Europe/Stockholm
    - VIRTUAL_HOST=api.dina-web
    - VIRTUAL_PORT=8080
  links:
    - dina-keycloak
    - dina-mysql

dina-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  links:
    - dina-wildfly
    - dina-keycloak
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

