fs-share:
  image: tianon/true
  volumes:
    - ./mysql-datadir:/var/lib/mysql:z
    - ./mysql-shr:/shr:z
    - ./mysql-autoload:/docker-entrypoint-initdb.d:ro
    - ./mysql-conf.d:/etc/mysql/conf.d:z
    - ./localdb-run.sh:/localdb-run.sh:rw
    - ./deployments:/opt/jboss/wildfly/standalone/deployments:z
    - ./wildfly-conf/configuration:/opt/keycloak/standalone/configuration:z

fs-api:
  image: tianon/true
  volumes:
    - ./nginx-conf:/etc/nginx/conf.d:rw
    - ./nginx-certs:/etc/nginx/ssl:rw
    - ./nginx-logs:/etc/nginx/logs:rw

db:
  image: mysql:latest
  command: "sh /localdb-run.sh"
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_ROOT_PASSWORD=password12
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak
  volumes_from:
    - fs-share

sso:
  image: dina/keycloak
  environment:
    - TZ=Europe/Stockholm
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloak
    - VIRTUAL_HOST=beta-sso.dina-web.net
    - VIRTUAL_PORT=8080
  ports:
    - "8080:8080"
  links:
    - db:mysql
  volumes_from:
    - fs-share

as:
  image: dina/collections-api
  environment:
    - TZ=Europe/Stockholm
  ports:
    - "9990:9990"
  links:
    - sso
    - db:dina-mysql





ws-api:
  image: nginx
  environment:
    - VIRTUAL_HOST=beta-api.dina-web.net
    - VIRTUAL_PORT=443
    - VIRTUAL_PROTO=https
    - CERT_NAME=dina-web.net
  links:
    - as
    - solr
  volumes_from:
    - fs-api

solr:
  image: dina/collections-solr
  links:
    - db:mysql
  ports:
    - "8983:8983"
